### ISSUE TITLE
Gitlab version of the hook only scans the first 20 files in a commit

### ISSUE THREAD

**Issue by simsandyca** [scanoss/webhook#11]
I submitted a PR https://github.com/scanoss/webhook/pull/10 with my fix. 

I'm testing the webhook with our on-prem gitlab installation (v 14.10).  I created and pushed a commit with 74 files.  Looking in the scanner log, it seemed like only 20 or so files were being scanned. 

The problem is that gitlab paginates list results - and you have to pull a "total_pages" header and repeat the request with a page count in the URL (at least that's how I fixed it). 

I was testing with python 3.11 and the latest version of the webhook master branch.

**Comment by eeisegn** [comment]
Accepted
